In [1]:
import numpy as np

In [2]:
class Node:
    def __init__(self, pattern, level, f):
        self.pattern = pattern
        self.level = level
        self.f = f

    def Children(self):
        """
        Create all possible childrens
        """
        children = []
        blank = np.where(self.pattern == 0)
        possible_positions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        for position in possible_positions:
            child = self.CreateChild(blank, position)
            if child is not None:
                children.append(child)
        return children

    def CreateChild(self, blank_position, possible_position):
        w, h = self.pattern.shape
        i = blank_position[0][0] + possible_position[0]
        j = blank_position[1][0] + possible_position[1]
        if 0 <= i and i < w and 0 <= j and j < h:
            new_pattern = self.pattern.copy()
            new_pattern[blank_position[0], blank_position[1]], new_pattern[i, j] = new_pattern[i, j], new_pattern[
                blank_position[0], blank_position[1]]
            return Node(new_pattern, self.level + 1, 0)
        else:
            return None

In [3]:
def In_Closed(closed,node):
    if len(closed) == 0:
        return True
    for closed_node in closed:
        if (closed_node.pattern == node.pattern).all() and closed_node.f < node.f:
            return False
        else:
            return True

def SolvePuzzle(start, goal):
    traveresd_nodes = []
    open_list = []
    close_list = []
    open_list.append(start)
    while True:
        current = open_list[0]
        print(current.pattern)
        print('----------------')
        traveresd_nodes.append(current)
        if (current.pattern == goal.pattern).all():
            print('Reached Goal')
            break
        for child in current.Children():
            child.f = Calculate_F(child, goal)
            if In_Closed(close_list,child):
                open_list.append(child)
        close_list.append(current)
        del open_list[0]
        open_list.sort(key=lambda x: x.f, reverse=False)

    return traveresd_nodes

def Calculate_F(start,goal,method='manhatan'):
    distance = 0
    w,_ = start.pattern.shape
    if method == 'manhatan':
        for i in range(w):
            for j in range(w):
                location = np.where(goal.pattern == start.pattern[i,j])
                distance += abs(location[0][0] - i)
                distance += abs(location[1][0] - j)
    elif method=='misplaced':
        distance += np.sum(goal.pattern != start.pattern)
    return distance+start.level

In [4]:
start = Node(np.array([0,1,3,4,2,5,7,8,6]).reshape((3,3)),0,0)
goal = Node(np.array([1,2,3,4,5,6,7,8,0]).reshape((3,3)),0,0)
steps = SolvePuzzle(start,goal)

[[0 1 3]
 [4 2 5]
 [7 8 6]]
----------------
[[1 0 3]
 [4 2 5]
 [7 8 6]]
----------------
[[1 2 3]
 [4 0 5]
 [7 8 6]]
----------------
[[1 2 3]
 [4 5 0]
 [7 8 6]]
----------------
[[1 2 3]
 [4 5 6]
 [7 8 0]]
----------------
Reached Goal
